services:
  notion2anki:

    container_name: notion2anki
    image: ghcr.io/techmovie/notion2anki:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - TZ=Asia/Shanghai
